# NCA Toolkit - Docker Compose 配置
# 本文件仅供参考，Zeabur 部署会自动使用 PREBUILT 镜像

version: '3.8'

services:
  nca-toolkit:
    image: xiangyugongzuoliu/nca-toolkit:latest
    container_name: nca-toolkit
    ports:
      - "8080:8080"
    environment:
      # ==================== 必需配置 ====================
      API_KEY: ${API_KEY}  # 必填：你的 API 密钥

      # ==================== 云存储配置（三选一）====================

      # 选项 A: Cloudflare R2（推荐）
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION:-auto}
      R2_PUBLIC_DOMAIN: ${R2_PUBLIC_DOMAIN}

      # 选项 B: Google Cloud Storage
      # GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      # GCP_SA_CREDENTIALS: ${GCP_SA_CREDENTIALS}

      # ==================== 性能调优（可选）====================
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-4}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-300}
      MAX_QUEUE_LENGTH: ${MAX_QUEUE_LENGTH:-0}

      # ==================== 系统配置（通常无需修改）====================
      PORT: "8080"
      WHISPER_CACHE_DIR: "/app/whisper_cache"
      LOCAL_STORAGE_PATH: "/tmp"
      PYTHONUNBUFFERED: "1"

    # 资源限制（根据实际情况调整）
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/toolkit/test"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s

    restart: unless-stopped

# 注意事项：
# 1. 在本地运行前，请创建 .env 文件并填写必需的环境变量
# 2. API_KEY 和云存储配置是必需的
# 3. 首次启动可能需要几分钟下载 Whisper 模型
# 4. 访问 http://localhost:8080 查看项目首页
